### PR TITLE
Bump to SDK 33, fix MIDI+BTLE

### LINKED ISSUE #77: Apps should use SDK 33
The Google Play Store require SDK 33 for new apps.
We should use 33 in case developers copy these apps.

When upgrading to 33 I started getting exceptions for missing Permissions for the MIDI+BTLE app.
I needed to add BLUETOOTH_SCAN and BLUETOOTH_CONNECT permissions.

### PR DESCRIPTION
**Pull request by philburk**
MIDI+BTLE needed new permissions.
I used a technique that allows asking for multiple permissions at one time.

Fixes #77

### CODE REVIEW

File: MidiBtlePairing/src/main/java/com/mobileer/example/midibtlepairing/MainActivity.java [hunk 1]
```diff
@@ -48,16 +48,26 @@
...
+ * App that creates a Device for a BLE-MIDI peripheral.
+ * The peripheral can then be used by other apps.
  */
 public class MainActivity extends Activity {
     private static final String TAG = "MidiBtlePairing";
     private static final String PACKAGE_NAME = "com.mobileer.example.midibtlepairing";
 
     private MidiManager mMidiManager;
     private OpenDeviceListAdapter mOpenDeviceListAdapter;
+    private static final int REQUEST_ID_MULTIPLE_PERMISSIONS = 100; // arbitrary
```
Comment (robertwu1) [inline MidiBtlePairing/src/main/java/com/mobileer/example/midibtlepairing/MainActivity.java:60]: I'm a little confused about the arbituary request code then checking for that later. Why do we need this?

Comment (philburk) [reply MidiBtlePairing/src/main/java/com/mobileer/example/midibtlepairing/MainActivity.java]: It is used to match the call to onRequestPermissionsResult() with the request.  The may be multiple requests in progress.

https://developer.android.com/training/permissions/requesting#manage-request-code-yourself

**Review by robertwu1 — APPROVED** [review]
